INSERT INTO categories('name','image') VALUES ('Công nghệ phần mềm','congnghephanmem.jpg');
INSERT INTO categories('name','image') VALUES ('Khoa học máy tính','khoahocmaytinh.png');
INSERT INTO categories('name','image') VALUES ('Kỹ thuật phần mềm','kythuatphanmem.jpg');
INSERT INTO categories('name','image') VALUES ('Trí tuệ nhân tạo và Robotics','aivarobotics.jpeg');
INSERT INTO categories('name','image') VALUES ('Mạng máy tính và truyền thông dữ liệu','mangmaytinhvatruyenthongdulieu.jpg');
INSERT INTO categories('name','image') VALUES ('An toàn thông tin','antoanthongtin.jpg');
INSERT INTO categories('name','image') VALUES ('Hệ thống quản lý thông tin','hethongquanlythongtin.jpeg');
INSERT INTO categories('name','image') VALUES ('Big Data và Machine Learning','bigdatavamachinelearning.jpg');
INSERT INTO categories('name','image') VALUES ('Phát triển phần mềm','phattrienphanmem.jpg');
INSERT INTO categories('name','image') VALUES ('Lập trình website','laptrinhweb.jpg');